#+TITLE: cquery layer

* Table of Contents                      :TOC_4_gh:noexport:
- [[#description][Description]]
  - [[#features][Features:]]
- [[#install][Install]]
  - [[#cquery-server][cquery server]]
  - [[#layer][Layer]]
- [[#configuration][Configuration]]

* Description
This layer adds [[https://github.com/cquery-project/cquery][cquery]] support.

** Features:
- Cross references (definitions, references, base/derived classes/methods, type instances, ...)
- Diagnostics
- Completion with =company-lsp=
- Semantic highlighting
- See more on [[https://github.com/cquery-project/cquery/wiki/Emacs]]

* Install
** cquery server
Install the =cquery= server. [[https://github.com/cquery-project/cquery/wiki/Getting-started][Instructions]].

** Layer
1) Add =cquery= to the =dotspacemacs-configuration-layers= list in =~/.spacemacs=.
2)
   #+BEGIN_SRC emacs-lisp
   (setq cquery-executable "/path/to/bin/cquery")
   #+END_SRC emacs-lisp
   If you need to expand =~= in the path, you can use =file-truename= like
   #+BEGIN_SRC emacs-lisp
   (setq cquery-executable (file-truename "~/cquery/build/release/bin/cquery"))
   #+END_SRC

* Configuration
cquery needs to know where to store index cache (=cquery-cache-dir=).
There are other initialization options such as the number of indexer threads, cache serialization format.
They have good default values. Refer to [[https://github.com/cquery-project/cquery/wiki/Initialization-options][Initialization options]] and set =cquery-extra-init-params= for more customization.
