# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/999d01b6-87c0-475c-8145-9e39bdf5d96b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-928121cb-6f8a-4036-8495-821b6210977f".device = "/dev/disk/by-uuid/928121cb-6f8a-4036-8495-821b6210977f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1EDB-ABCC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  #swapDevices =
  #  [ { device = "/dev/disk/by-uuid/ff6bf616-f6e2-499e-8287-dbe3915946ab"; }
  #  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
