#!/usr/bin/env bash

#Clone spacemacs
if [[ -a ~/.emacs.d ]]; then
    echo "WARNING: ~/.emacs.d found -- skipping spacemacs checkout"
else
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
fi
