#!/bin/sh

#Setup paths
. ./go/.profile.d/goenv.sh

#Spacemacs go-layer dependencies..
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v golang.org/x/tools/cmd/guru
go get -u -v golang.org/x/tools/cmd/gorename
go get -u -v golang.org/x/tools/cmd/goimports
go get -u -v github.com/godoctor/godoctor
go install github.com/godoctor/godoctor
