#+TITLE: TRFKACD (The Repo Formerly Known As CormacC's Dotfiles)
#+AUTHOR: Cormac Cannon
#+EMAIL: cormac.cannon@neuromoddevices.com
#+LANGUAGE: en
#+COPYRIGHT: Neuromod Devices Ltd. 2023
#+DATE: 2023-10-27

# HTML EXPORT SETUP
# 1. Apply a theme
#+SETUPFILE: ~/Documents/templates/org-html-themes/org/theme-readtheorg.setup

# 2. Ensure exports include both source block contents and any results
#+PROPERTY: header-args :exports both

# 3. Specify styles for ODT (and DOCX) export

#+ODT_STYLES_FILE: ("~/Documents/templates/nmd-template.odt" ("styles.xml" "content.xml" "Pictures/1000000000000A4F000004650AA167B89A2F5561.jpg"))

# Startup options : Want to view rendered versions of latex fragments (equations etc.) by default
#+STARTUP:: latexpreview


Some introductory text

* Table of Contents                                         :TOC_4_gh:noexport:
- [[#overview][Overview]]
- [[#known-issues][Known issues]]
- [[#future-plans][Future plans]]
  - [[#move-to-a-nixos-based-setup][Move to a NixOS based setup]]
- [[#provisioning-a-new-accountinstallation][Provisioning a new account/installation]]
  - [[#install-nix][Install Nix]]
  - [[#install-home-manager][Install Home Manager]]
    - [[#add-the-home-manager-channel][Add the home manager channel]]
    - [[#install-home-manager-1][Install Home Manager]]
  - [[#apply-the-home-manager-flake][Apply the Home Manager flake]]
  - [[#post-installation-activities][Post-installation activities]]
    - [[#generate-a-unique-ssh-key-for-this-installation][Generate a unique SSH key for this installation]]
- [[#maintenance][Maintenance]]
  - [[#updating-packages][Updating packages]]
  - [[#managing-generations][Managing generations]]
    - [[#list-generations][List generations]]
    - [[#delete-obsolete-generations][Delete obsolete generations]]
    - [[#rollback-to-a-previous-generation][Rollback to a previous generation]]

* Overview
My homefolder configuration, now managed as a Nix flake using Home Manager.
Formerly managed using the [[https://github.com/cormacc/dotmodule][dotmodule]] gem.

* Known issues
Applications requiring OpenGL don't work when installed using Home Manager.
This is an upstream issue with a number of viable workarounds, but for now I'm
just installing OpenGL apps (just Kitty and Alacritty so far) from the Arch repositories.
This issue should disappear if/when I move to NixOS.

* Future plans

** TODO Move to a NixOS based setup
I'm currently using Nix and Home Manager, sitting on top of Arch (or rather Manjaro) linux as a crutch.
Once I'm happy with development flow using Nix entirely (and that I can manage to install various obscure development dependencies without the AUR), switch over

* Provisioning a new account/installation
** Install Nix
Installed using the [[https://zero-to-nix.com/start/install][zero-to-nix]] script rather than the official installer -- this enables flakes by default, saving a manual step.
#+begin_src shell
  curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
#+end_src

** Install Home Manager
Paraphrased from the [[https://nix-community.github.io/home-manager/index.html#ch-installation][official docs]].

*** Add the home manager channel
#+begin_src shell
  nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
  nix-channel --update
#+end_src

*** Install Home Manager
#+begin_src shell
  nix-shell '<home-manager>' -A install
#+end_src

** Apply the Home Manager flake
To finish provisioning your account, run the command provided below to rebuild the configuration:
#+begin_src shell
  home-manager switch --flake './dotfiles#<host>' --impure -b backup
#+end_src
e.g.
#+begin_src shell
  home-manager switch --flake './dotfiles#xps15' --impure -b backup
#+end_src


** Post-installation activities

*** Generate a unique SSH key for this installation
Use the newer ED25519 algorithm (per [[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent][Github instructions]]).
#+begin_src shell
  ssh-keygen -t ed25519 -C "your_email@example.com"
#+end_src

Then add the new key via Gitlab settings.

* Maintenance
** Updating packages
Nix freezes the revision of nixpkgs used initially (in [[./nix/home/flake.lock]]) to ensure the build is reproducible.
To update, run the following commands.
#+begin_src shell
  sudo -i nix-channel --update
#+end_src

Then re-apply the flake to update.

** Managing generations
A new generation (configuration revision) is built each time we run `home-manager switch`.

*** List generations
#+begin_src shell
  home-manager generations
#+end_src

#+RESULTS:
: 2023-10-27 00:50 : id 19 -> /nix/store/5h9hisgf0jhygihvkanyvv19dz6s8gv4-home-manager-generation

*** Delete obsolete generations
E.g. to delete the first 18 generations...
#+begin_src shell
  home-manager remove-generations $(seq 1 18)
#+end_src

*** Rollback to a previous generation
Home-manager doesn't provide explicit rollback in the sense that nix does, but you can
easily manually activate a given generation (and potentially delete later problematic
 generations).
To activate:
1. Run `home-manager generations` and locate the generation of interest.
2. Open a shell to the folder listed for the generation in question.
3. Run the `activate` script in that folder
4. (Optionally) remove (delete) any later unwanted generations.
