#+LINK: task file:TASKS.org::#%s
#+LINK: archive file:TASKS.archive.org::#%s
#+SETUPFILE: ./TASKS.local.org
#+SETUPFILE: ./TASKS.setup.org

* DONE [#A] Extract agent skills and extensions as new flake
CLOSED: [2026-05-07 Thu 22:46]
:PROPERTIES:
:CUSTOM_ID: 9e134ad1-6a9c-4e7d-9fe9-82df2634224e
:STARTED: [2026-05-07 Thu 21:25]
:ARCHIVED: [2026-05-07 Thu 23:01]
:END:
:LOGBOOK:
- State "DONE"      from "STARTED"   [2026-05-07 Thu 22:46]
- State "STARTED"   from "TODO"      [2026-05-07 Thu 21:25]
:END:
#+IMPORT: [[plan:2026-05-07-extract-agent-skills.org]]
Most of the recent activity in this repo is iterating on agent skills. Dotfiles/system config should be relatively static. Let's extract these as follows:
- Extract skills and extensions to a new git-repo / flake -- it'll be at github:cormacc/dotagents
- The new repo will contain only the skills and extensions -- the actual agent installation will remain here in agents.nix
- The new repo will be a monorepo -- initially it'll have the existing package definition for the org-memory family of skills, but later at least one other package definition for a clojure-development related set of skills
- the local/dev install mechanism for the skills and extensions will remain symlink based -- i.e. editable and reloadable immediately in-place without a home-manager switch iteration. If not straightforward via flake, including the new repo as a submodule here is an acceptable compromise.

* CANCELLED [#C] Update nixGL flake URL :nix:
CLOSED: [2026-05-06 Wed 09:37]
:PROPERTIES:
:CUSTOM_ID: 862e9ecf-6992-40e9-b2e2-597edee1ccfa
:BLOCKED-BY: url:https://github.com/nix-community/nixGL/pull/187
:STARTED: [2026-05-06 Wed 09:37]
:ARCHIVED: [2026-05-06 Wed 09:37]
:END:
:LOGBOOK:
- State "STARTED" from "WAITING" [2026-05-06 Wed 09:37]
- State "TODO" from "STARTED" [2026-05-06 Wed 09:37]
- State "CANCELLED" from "TODO" [2026-05-06 Wed 09:37]
:END:
Waiting on an upstream fix for an nvidia-open issue Cancelled - eliminated use of nixGL -- use targets.genericLinux.enable instead on non-NixOS installs. See https://nix-community.github.io/home-manager/index.xhtml#sec-usage-gpu-non-nixos

** DONE [#B] Add flake profile for new framework desktop
CLOSED: [2026-05-19 Tue 16:32]
:PROPERTIES:
:CUSTOM_ID: a2d48659-3143-46f7-a6b3-995f73292d7b
:CREATED: [2026-05-19 Tue 13:46]
:ARCHIVED: [2026-05-19 Tue 16:32]
:END:
:LOGBOOK:
- Created [2026-05-19 Tue 13:46]
- State "DONE" from "TODO" [2026-05-19 Tue 16:32]
:END:
#+IMPORT: [[plan:2026-05-19-add-flake-profile-for-new-framework-desk.org]]
I have a framework desktop with a fresh install of NixOS from the live CD, with no post-install modifications.
Add a new host profile in this flake for the desktop.
It's the AMD Ryzen AI Max+ 395 configuration with 128GB RAM and 2x4TB SSDs for storage. The NixOS installation uses a single 4TB SSD.
It should largely replicate the existing sway-based profile for xps15 but replace hardware specifics (nvidia etc.) with modules appropriate for the desktop hardware. The machine is intended as a local LLM server, so include the following:
- Lemonade as a local AI server (via this repo: https://github.com/noamsto/nix-amd-ai)
- Separate nixos and home-manager, as with the existing xps15 configuration -- retain the 'nos' and 'hms' shell aliases.
- SSH access for my default cormacc user
- Use 'strix' as the configuration id in nixosConfigurations
- Provide a bootstrap shell script streamlining application of the new nixosConfiguration on top of a base NixOS install
