# input "*" equals all input methods
# to specify settings for a specific input method, use its identifier instead.
# query the connected input methods: `swaymsg -t get_inputs`

input * {
    # toggles through configured layouts via caps-lock
    # query the available layout toggles: `localectl list-x11-keymap-options | grep grp:`
    # query the available led indicators: `localectl list-x11-keymap-options | grep grp_led`
    # enables caps-lock led if not the first layout selected
    # regular caps-lock behavior can be reached using shift+caps-lock
    # xkb_options grp:caps_toggle,grp_led:caps

    xkb_options caps:escape_shifted_capslock

    # query the available layouts: `localectl list-x11-keymap-layouts`
    xkb_layout "ie,gb,us"

    # query the available variants for a given layout: `localectl list-x11-keymap-variants de`
    # list in the same order as the layouts - empty equals the default layout
    #xkb_variant ","
}

set $menu_launch Execute (w/W)ww, (e/E)ditor, (v)m, (f/F)ileman/sudo, (m)plab
mode "$menu_launch" {
    bindsym w exec chromium, mode "default"
    bindsym Shift+w exec firefox, mode "default"
    bindsym e exec emacs, mode "default"
    bindsym Shift+e exec code, mode "default"
    bindsym v exec virt-manager, mode "default"
    bindsym f exec ranger, mode "default"
    bindsym Shift+f exec gksu ranger, mode "default"
    bindsym m exec mplab_ide, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+x mode "$menu_launch"
