#!/bin/bash
set -e

#	screen-backlight
#		For when you are running leeenux on a Mac and it needs some help
#
#	Usage:
#		screen-backlight	{up,down,total,off}
#
# For this to work without root privileges, you'll need to be a member of the 'video' group
# and place a file called something like '90-backlight.rules' with the following content in
# '/etc/udev/rules.d/'
#
# SUBSYSTEM=="backlight", ACTION=="add", \
#         RUN+="/bin/chgrp video %S%p/brightness", \
#         RUN+="/bin/chmod g+w %S%p/brightness"
#


BLDIR=/sys/class/backlight/acpi_video0
GMDIR=/sys/class/backlight/gmux_backlight
if [[ ! -d $BLDIR ]]; then
	if [[ -d $GMDIR ]]; then
		BLDIR=$GMDIR
	else
		echo "Check what directory your backlight is stored in /sys/class/backlight/"
		exit 1
	fi
fi

SET_VALUE=0

MAX=$(cat "$BLDIR/max_brightness")
if [ $MAX -lt "0" ]; then
	MAX=1000
	echo "Defaulting MAX to $MAX"
fi

BLFILE="$BLDIR/brightness"
BACKLIGHT=$(cat $BLFILE)

if [ $BACKLIGHT -gt "$MAX" ]; then
  BACKLIGHT=$MAX
  echo "Defaulting current brightness to $BACKLIGHT"
fi

case $1 in

	up)
		if [ $BACKLIGHT -lt 1 ]; then
			TOTAL=1
		else
			TOTAL=`expr $BACKLIGHT + $BACKLIGHT`
		fi
		if [ $TOTAL -gt "$MAX" ]; then
			TOTAL=$MAX
		fi
		SET_VALUE=1
		;;
	down)
		if [ $BACKLIGHT -gt 1 ]; then
			TOTAL=`expr $BACKLIGHT / 2`
		else
			TOTAL=0
		fi
		SET_VALUE=1
		;;
	total)
	TEMP_VALUE=$BACKLIGHT
	while [ $TEMP_VALUE -lt "$MAX" ]; do
		TEMP_VALUE=`expr $TEMP_VALUE + 1`
		if [ $TEMP_VALUE -gt "$MAX" ]; then TEMP_VALUE=$MAX; fi
		echo $TEMP_VALUE > $BLFILE
	done
		;;
	off)
	TEMP_VALUE=$BACKLIGHT
	while [ $TEMP_VALUE -gt "0" ]; do
		TEMP_VALUE=`expr $TEMP_VALUE - 1`
		if [ $TEMP_VALUE -lt "0" ]; then TEMP_VALUE=0; fi
		echo $TEMP_VALUE > $BLFILE
	done
		;;
	*)
		echo "Use: screen-backlight up|down|total|off"
		;;
esac

if [ $SET_VALUE -eq "1" ]; then
	echo "Setting brightness to $TOTAL"
	echo $TOTAL > $BLFILE
fi
