#!/usr/bin/env ruby

require 'xrandr'
require 'thor'

# CLI wrapper to autoconfigure connected displays using Xrandr::Configurator
class DisplayConfig < Thor

  class_option :dryrun, type: :boolean, default: false
  class_option :int, type: :string,
                     default: Xrandr::Configurator::DEFAULT_INTERNAL_PORT,
                     desc: 'Port (regex )for internal display.'
  class_option :ext, type: :string, default: nil,
                     desc: 'Preferred port for external display. First available port used if disconnected or not specified.'
  class_option :int_res, type: :string,
                         default: Xrandr::Configurator::DEFAULT_INTERNAL_RES,
                         desc: 'Resolution for fallback internal display detection'

  desc "auto", "Autodetect and configure connected displays."
  def auto
    configurator = Xrandr::Configurator.new
    configurator.internal_display_matcher = /#{options[:int]}/
    configurator.internal_display_resolution = options[:int_res]
    command = configurator.auto(options[:dryrun], options[:ext])
    puts command
  end

end

DisplayConfig.start(ARGV)
